In [42]:
import pandas as pd
import numpy as np

In [22]:
f = "C:/Users/IlhamAkbarRamadhan/mediaagentur-in.berlin/Ilham - Documents/VSCODE/py/imports-85.data"
headers = ["symboling","normalized-losses","make","fuel-type","aspiration","num-of-doors","body-style",
"drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
"num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower", "peak-rpm","city-mpg","highway-mpg","price"]

In [27]:
df = pd.read_csv(f, header=None)
df.columns = headers

In [24]:
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [31]:
path="C:/Users/IlhamAkbarRamadhan/mediaagentur-in.berlin/Ilham - Documents/VSCODE/py/automobile.csv"
df.to_csv(path)

In [36]:
df = pd.read_csv(
    "C:/Users/IlhamAkbarRamadhan/mediaagentur-in.berlin/Ilham - Documents/VSCODE/py/automobile.csv")

In [48]:
df1=df.replace('?',np.NaN)

In [49]:
df = df1.dropna(subset=["price"], axis=0)
df.head(20)

,Unnamed: 0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,3,2,164,audi,gas,std,four,sedan,fwd,front,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,4,2,164,audi,gas,std,four,sedan,4wd,front,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,5,2,NaN,audi,gas,std,two,sedan,fwd,front,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,6,1,158,audi,gas,std,four,sedan,fwd,front,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,7,1,NaN,audi,gas,std,four,wagon,fwd,front,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,8,1,158,audi,gas,turbo,four,sedan,fwd,front,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,10,2,192,bmw,gas,std,two,sedan,rwd,front,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,11,0,192,bmw,gas,std,four,sedan,rwd,front,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,12,0,188,bmw,gas,std,two,sedan,rwd,front,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,13,0,188,bmw,gas,std,four,sedan,rwd,front,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,14,1,NaN,bmw,gas,std,four,sedan,rwd,front,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,15,0,NaN,bmw,gas,std,four,sedan,rwd,front,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,16,0,NaN,bmw,gas,std,two,sedan,rwd,front,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,17,0,NaN,bmw,gas,std,four,sedan,rwd,front,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
20,20,0,81,chevrolet,gas,std,four,sedan,fwd,front,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575

In [46]:
df.describe(include = "all")

,Unnamed: 0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,201.000000,201.000000,164,201,201,201,199,201,201,201,...,201.000000,201,197,197,201.000000,199,199,201.000000,201.000000,201
unique,NaN,NaN,51,22,2,2,2,5,3,2,...,NaN,8,38,36,NaN,58,22,NaN,NaN,186
top,NaN,NaN,161,toyota,gas,std,four,sedan,fwd,front,...,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,8921
freq,NaN,NaN,11,32,181,165,113,94,118,198,...,NaN,92,23,19,NaN,19,36,NaN,NaN,2
mean,102.900498,0.840796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,126.875622,NaN,NaN,NaN,10.164279,NaN,NaN,25.179104,30.686567,NaN
std,59.234956,1.254802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.546834,NaN,NaN,NaN,4.004965,NaN,NaN,6.423220,6.815150,NaN
min,0.000000,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,53.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,103.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,154.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,204.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [50]:
df.to_csv("automobile.csv", index=False)